/* 10 Oct 2026 — N/A on an inspection item (QA request). Run: node qana.test.js */
const H = require('./harness.js');
const vm = require('vm');
const { ok, report, grab, html } = H;
const eq = (got, want, name) => ok(name, JSON.stringify(got) === JSON.stringify(want));
const sb = { console, fmt: x => String(x), state: {} };
vm.createContext(sb);
vm.runInContext(['qcNaRadio', 'qcNaGate', 'qcVerifyRows', 'qcVerifyGate', 'qcVerifyRecord', 'qcVerifyFailed'].map(grab).join('\n'), sb);
vm.runInContext("var QC_NA_CHECK=[7]; var QC_NA_VERIFY=[0]; var QC_VERIFY=[{k:'price',label:'Price'},{k:'batch',label:'Batch'},{k:'dates',label:'Dates'}];", sb);
const g = (m, v, r) => vm.runInContext('qcNaGate', sb)(m, v, r);
const p8 = i => ['pass','pass','pass','pass','pass','pass','pass', i];
eq(g(p8('na'), null, ''), 'You marked something N/A: write in Remarks why it does not apply (at least 5 characters).', 'N/A without a reason is refused');
eq(g(p8('na'), null, 'No pallet at pack stage'), null, 'N/A with a reason passes');
eq(g(['na','pass','pass','pass','pass','pass','pass','pass'], null, 'because'), 'N/A is not allowed on that item. Mark it Pass or Fail.', 'N/A on packaging is refused');
eq(g(null, ['pass','na','pass'], 'because'), 'N/A is not allowed on that item. Mark it Pass or Fail.', 'N/A on batch match is refused');
eq(g(null, ['na','pass','pass'], 'No price on this pack'), null, 'N/A on price with a reason passes');
eq(g(p8('pass'), ['pass','pass','pass'], ''), null, 'no N/A, no reason needed');
const vg = vm.runInContext('qcVerifyGate', sb);
eq(vg(['na','pass','pass'], { priceSeen: '' }, true), null, 'price N/A: no price to write down');
ok('price not N/A still asks for the price', !!vg(['pass','pass','pass'], { priceSeen: '' }, true));
ok('an unmarked item is still refused', !!vg(['', 'pass', 'pass'], {}, false));
const rec = vm.runInContext('qcVerifyRecord', sb)(['na','pass','pass'], { priceSeen: 1250 });
eq(rec.length, 3, 'N/A price: no priceSeen row'); eq(rec[0].result, 'na', 'record keeps na');
eq(vm.runInContext('qcVerifyFailed', sb)(['na','pass','pass']), false, 'N/A is not a fail');
const rows = vm.runInContext('qcVerifyRows', sb)({}, ['', '', ''], 'f', 'x()');
ok('price row offers N/A', (rows.match(/N\/A/g) || []).length === 1);
ok('checklist renderers offer N/A only on index 7', (html.match(/QC_NA_CHECK\.indexOf\(i\)>-1\?qcNaRadio/g) || []).length === 3);
ok('all 3 submit paths gate N/A', /qcNaGate\(lotQAForm\.marks/.test(html) && /qcNaGate\(f\.marks,f\.verify/.test(html) && /qcNaGate\(dispQAForm\.marks/.test(html));
ok('printed reports show N/A', /c\.result==='na'\?'N\/A'/.test(html) && /v==='na' \? '<span class="muted">N\/A/.test(html));
report();
